name: deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: Cygra/css_magic@master
      env:
        BUILD_SCRIPT: yarn && yarn run deploy
